### ISSUE TITLE
Pie chart rendering discrepancy

### ISSUE THREAD

**Issue by DoParkEQ** [EQWorks/chart-system#132]
The issue is originally found from overlord's geo cohort report. The pie chart shows the fraction of the entire circle when the number is 100%

Could be overlord specific.
 
![Screen Shot 2021-06-10 at 9 07 15 PM](https://user-images.githubusercontent.com/59836949/121616132-49c7bd80-ca30-11eb-84a2-778829979ee5.png)

**Comment by geoerika** [comment]
Not overlord specific....

**Comment by geoerika** [comment]
@DoParkEQ I don't quite fully understand what is the issue with showing 100% here. This is how it should be. The Pie chart adjusts the percentages of slices depending on what data is visible. It will eliminate all unselected data from the whole and recalculates percentages of the visible slices from the whole calculated based on the visible slices. So, when you have only one visible data set left, it will be 100%.
