### ISSUE TITLE
Plotly charts - tooltip format, y-axis label & %

### ISSUE THREAD

**Issue by geoerika** [EQWorks/chart-system#175]
**Problem to solve:**
Investigate & change tooltip format, adding y-axis label, adding % to y-axis when percentage is used in a widget

**Reference:**
https://github.com/EQWorks/widget-studio/pull/143#issuecomment-1204418817

**Comment by kc-leung** [comment]
@YizhiCatherineZhang Is there a design for the tooltip format ? What should I change??
